<Project>
  <PropertyGroup>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>

  <PropertyGroup>
    <Version>1.2.0</Version>
    <Authors>Build Workbench</Authors>
    <Product>DigYourWindows</Product>
    <Description>Windows 深度诊断工具</Description>
    <Copyright>Copyright © Build Workbench 2025-2026</Copyright>
    <RepositoryUrl>https://github.com/build-workbench/dig-your-windows</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>
</Project>
